name = "internet-meme-test"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB" # 统一使用 DB 绑定
database_name = "internet-meme-test"
database_id = "e997e2da-a45c-4857-b196-f9cf39674cc2"
