import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased font-serif">
        <div className="fixed-background" />
        <div className="mobile-container">
          <div className="mobile-content">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
